<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" href="css/style.css">
	<title> <?php echo $pageTitle;?></title>
	
</head>

<body class="container">

	<header>
		
			<h1>Dominique Dorvil</h1>
		<a href="dom_index.php">
			<img src="images/dompic.jpg" alt="me">
		</a>
	</header>

	<aside>
		<ul>
			<li> 🎓 : CS & Digital Media Studies(NS)</li>
			<li>Hometown: 🗽</li>
			<li>Fun Facts: ✝️🎨🛍📝♌️🇭🇹💍</li>
		</ul>
	</aside>

</body>
