<nav class="menu">

		<ul>

			<li><a href="index.php">Home</a></li>

			<li><a href="humblestart.php">Humble Beginnings</a></li>

			<li><a href="campuslife.php">Campus Life</a></li>

			<li><a href="internships.php">Internships</a></li>

		</ul>

</nav>

<nav>
    <ul>
    <li><a href="dom_index.php">Home</a></li>
    <li><a href="v_index.php">Home</a></li>
    <li><a href="mp_index.php">Home</a></li>
    </ul>
</nav>
